# frozen_string_literal: true

source 'https://rubygems.org'

gem 'alt_memery'
gem 'grape'

group :lint do
	gem 'rubocop'
	gem 'rubocop-performance'
	gem 'rubocop-rspec'
	gem 'rubocop-sequel'
end

group :test do
	gem 'rack-test'
	gem 'rspec'
	gem 'warning'
end
